AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This template creates a customer-managed IAM policy for ZPA Privileged Remote Access (PRA)
  to grant the necessary permissions for creating and managing disposable jump boxes and other resources.

Parameters:
  TargetAccountId:
    Type: String
    Description: The AWS Account ID where the resources will be managed.
  TargetRegion:
    Type: String
    Description: The AWS Region where the resources will be managed.

Resources:
  PrivilegedDesktopsIAMPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "ZPA-PRA-Cross-Account-Policy-${TargetRegion}"
      Description: "Policy for ZPA Privileged Remote Access to manage required AWS resources."
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "Statement11"
            Effect: "Allow"
            Action:
              - "ec2:CreateVpc"
            Resource:
              - !Sub "arn:aws:ec2:${TargetRegion}:${TargetAccountId}:vpc/*"
            Condition:
              StringLike:
                "aws:RequestTag/Name": "*ZPA-PRA*"
          - Sid: "Statement12"
            Effect: "Allow"
            Action:
              - "ec2:CreateSubnet"
            Resource:
              - !Sub "arn:aws:ec2:${TargetRegion}:${TargetAccountId}:subnet/*"
            Condition:
              StringLike:
                "aws:RequestTag/Name": "*ZPA-PRA*"
          - Sid: "Statement13"
            Effect: "Allow"
            Action:
              - "ec2:CreateRouteTable"
            Resource:
              - !Sub "arn:aws:ec2:${TargetRegion}:${TargetAccountId}:route-table/*"
            Condition:
              StringLike:
                "aws:RequestTag/Name": "*ZPA-PRA*"
          - Sid: "Statement14"
            Effect: "Allow"
            Action:
              - "ec2:CreateInternetGateway"
            Resource:
              - !Sub "arn:aws:ec2:${TargetRegion}:${TargetAccountId}:internet-gateway/*"
            Condition:
              StringLike:
                "aws:RequestTag/Name": "*ZPA-PRA*"
          - Sid: "Statement15"
            Effect: "Allow"
            Action:
              - "ec2:CreateSecurityGroup"
            Resource:
              - !Sub "arn:aws:ec2:${TargetRegion}:${TargetAccountId}:security-group/*"
            Condition:
              StringLike:
                "aws:RequestTag/Name": "*ZPA-PRA*"
          - Sid: "Statement16"
            Effect: "Allow"
            Action:
              - "ec2:CreateSubnet"
              - "ec2:CreateRouteTable"
              - "ec2:CreateSecurityGroup"
            Resource:
              - !Sub "arn:aws:ec2:${TargetRegion}:${TargetAccountId}:vpc/*"
            Condition:
              StringLike:
                "ec2:ResourceTag/Name": "*ZPA-PRA*"
          - Sid: "Statement23"
            Effect: "Allow"
            Action:
              - "ec2:ModifyVpcAttribute"
              - "ec2:DeleteVpc"
            Resource:
              - !Sub "arn:aws:ec2:${TargetRegion}:${TargetAccountId}:vpc/*"
            Condition:
              StringLike:
                "ec2:ResourceTag/Name": "*ZPA-PRA*"
          - Sid: "Statement24"
            Effect: "Allow"
            Action:
              - "ec2:CreateRoute"
              - "ec2:AssociateRouteTable"
              - "ec2:DeleteRouteTable"
              - "ec2:DeleteRoute"
              - "ec2:DisassociateRouteTable"
            Resource:
              - !Sub "arn:aws:ec2:${TargetRegion}:${TargetAccountId}:route-table/*"
            Condition:
              StringLike:
                "ec2:ResourceTag/Name": "*ZPA-PRA*"
          - Sid: "Statement29"
            Effect: "Allow"
            Action:
              - "ec2:AssociateRouteTable"
              - "ec2:DisassociateRouteTable"
            Resource:
              - !Sub "arn:aws:ec2:${TargetRegion}:${TargetAccountId}:subnet/*"
            Condition:
              StringLike:
                "ec2:ResourceTag/Name": "*ZPA-PRA*"
          - Sid: "Statement28"
            Effect: "Allow"
            Action:
              - "ec2:AttachInternetGateway"
              - "ec2:DetachInternetGateway"
            Resource:
              - !Sub "arn:aws:ec2:${TargetRegion}:${TargetAccountId}:vpc/*"
            Condition:
              StringLike:
                "ec2:ResourceTag/Name": "*ZPA-PRA*"
          - Sid: "Statement25"
            Effect: "Allow"
            Action:
              - "ec2:AttachInternetGateway"
              - "ec2:DetachInternetGateway"
              - "ec2:DeleteInternetGateway"
            Resource:
              - !Sub "arn:aws:ec2:${TargetRegion}:${TargetAccountId}:internet-gateway/*"
            Condition:
              StringLike:
                "ec2:ResourceTag/Name": "*ZPA-PRA*"
          - Sid: "Statement26"
            Effect: "Allow"
            Action:
              - "ec2:AuthorizeSecurityGroupIngress"
              - "ec2:DeleteSecurityGroup"
              - "ec2:RevokeSecurityGroupIngress"
            Resource:
              - !Sub "arn:aws:ec2:${TargetRegion}:${TargetAccountId}:security-group/*"
            Condition:
              StringLike:
                "ec2:ResourceTag/Name": "*ZPA-PRA*"
          - Sid: "Statement27"
            Effect: "Allow"
            Action:
              - "ec2:ModifySubnetAttribute"
              - "ec2:DeleteSubnet"
            Resource:
              - !Sub "arn:aws:ec2:${TargetRegion}:${TargetAccountId}:subnet/*"
            Condition:
              StringLike:
                "ec2:ResourceTag/Name": "*ZPA-PRA*"
          - Sid: "Statement3"
            Effect: "Allow"
            Action:
              - "iam:GetRole"
              - "iam:ListAttachedRolePolicies"
            Resource:
              - !Sub "arn:aws:iam::${TargetAccountId}:role/DJB-Cross-Account-Role"
          - Sid: "Statement33"
            Effect: "Allow"
            Action:
              - "iam:GetPolicy"
              - "iam:GetPolicyVersion"
            Resource:
              - !Sub "arn:aws:iam::${TargetAccountId}:policy/ZPA-PRA-Cross-Account-Policy-${TargetRegion}"
          - Sid: "Statement4"
            Effect: "Allow"
            Action:
              - "ec2:DescribeAvailabilityZones"
              - "ec2:DescribeInternetGateways"
              - "ec2:DescribeVpcs"
              - "ec2:DescribeSecurityGroups"
              - "ec2:DescribeRouteTables"
              - "ec2:DescribeSubnets"
              - "ec2:DescribeInstances"
              - "ec2:DescribeInstanceStatus"
              - "ec2:CreateTags"
              - "ec2:DescribeImages"
              - "ec2:DescribeInstanceTypes"
              - "cloudformation:DescribeStacks"
              - "ec2:DescribeKeyPairs"
              - "ec2:CreateKeyPair"
            Resource: "*"
          - Sid: "Statement5"
            Effect: "Allow"
            Action:
              - "cloudformation:CreateStack"
              - "cloudformation:DeleteStack"
              - "cloudformation:DescribeStackEvents"
            Resource:
              - !Sub "arn:aws:cloudformation:${TargetRegion}:${TargetAccountId}:stack/*"
          - Sid: "RunInstancesWithTagRestrictions"
            Effect: "Allow"
            Action: "ec2:RunInstances"
            Resource:
              - !Sub "arn:aws:ec2:${TargetRegion}:${TargetAccountId}:instance/*"
            Condition:
              StringLike:
                "aws:RequestTag/Name": "ZPA-PRA*"
          - Sid: "RemainingRunInstancePermissionsNonResource"
            Effect: "Allow"
            Action: "ec2:RunInstances"
            Resource:
              - !Sub "arn:aws:ec2:${TargetRegion}::image/*"
              - !Sub "arn:aws:ec2:${TargetRegion}:${TargetAccountId}:volume/*"
              - !Sub "arn:aws:ec2:${TargetRegion}:${TargetAccountId}:network-interface/*"
              - !Sub "arn:aws:ec2:${TargetRegion}:${TargetAccountId}:key-pair/*"
              - !Sub "arn:aws:ec2:${TargetRegion}:${TargetAccountId}:security-group/*"
          - Sid: "EC2RunInstancesVpcSubnet"
            Effect: "Allow"
            Action: "ec2:RunInstances"
            Resource:
              - !Sub "arn:aws:ec2:${TargetRegion}:${TargetAccountId}:subnet/*"
            Condition:
              StringLike:
                "ec2:ResourceTag/Name": "*ZPA-PRA*"
          - Sid: "AllowInstanceActionsTagBased"
            Effect: "Allow"
            Action:
              - "ec2:ModifyInstanceAttribute"
              - "ec2:TerminateInstances"
            Resource:
              - !Sub "arn:aws:ec2:${TargetRegion}:${TargetAccountId}:instance/*"
            Condition:
              StringLike:
                "ec2:ResourceTag/Name": "ZPA-PRA*"

Outputs:
  PolicyArn:
    Description: "The ARN of the created IAM policy."
    Value: !Ref PrivilegedDesktopsIAMPolicy